version: '3'
services:
  app:
    build: .
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - db
    links:
      - db
    command: bash -c  'cd /app/blogs/ && php artisan serve --host=0.0.0.0' 
    volumes:
      - ./:/app
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
